### ISSUE TITLE
Updated project is requiring a higher min deployment target

### ISSUE THREAD

**Issue by DianSSIE** [zoho/SalesIQ-Mobilisten-Cordova#10]
`

        
        [error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod "Mobilisten":
        In snapshot (Podfile.lock):
        Mobilisten (= 6.0.0)

        In Podfile:
        CordovaPluginsStatic (from '../capacitor-cordova-ios-plugins') was resolved to 5.4.2, which depends on
        Mobilisten (= 6.0.1)
        
        Specs satisfying the 'Mobilisten (= 6.0.0), Mobilisten (= 6.0.1)' dependency were found, but they required a
        higher minimum deployment target.`
        
Hi, we upgraded our capacitor project and the tool ionic uses to allow usage of cordova plugins in the project is starting to require Mobilisten to have a higher min deployment target.

Looking in the ios repo at the Mobilisten.podspec I see the min deployment target is 11?

https://developer.apple.com/support/app-store/

**Comment by DianSSIE** [comment]
Or is it the other way around?

**Comment by venkatesh-ramesh-12517** [comment]
Hello @DianSSIE 

Thank you for reaching out about the issue with the `SalesIQ-Mobilisten-Cordova` plugin.
 
Steps to Fix the Deployment Target Issue:
1. Update the SalesIQ Plugin: Make sure you have the latest version of the`SalesIQ` plugin:

```
cordova plugin update cordova-plugin-salesiq
```
2. Set the Minimum Deployment Target to iOS 12.0: Add this line to your`config.xml` file:

```
<platform name="ios">
    <preference name="deployment-target" value="12.0"/>
</platform>
```

3. Update`Podfile`: Open`platforms/ios/Podfile` and change this line to:
 
```
platform :ios, '12.0'
```
4. Then run:

```
cd platforms/ios
pod install
```

5. Rebuild Your iOS Project: After updating the deployment target, rebuild your iOS project:

```
rm -rf platforms/ios/build
cordova build ios
```
 
If the issue persists, please contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to investigate this issue further for you.
 
Regards,
Venkatesh R,
Zoho SalesIQ.
