### ISSUE TITLE
Equivalent to isSDKEnabled in cordova 

### ISSUE THREAD

**Issue by alaaahmedmu** [zoho/SalesIQ-Mobilisten-Cordova#11]
I am asking about if there is an equivalent to isSDKEnabled which is in android sdk here https://www.zoho.com/salesiq/help/developer-guides/android-is-sdk-enabled-2-0.html to be available in the cordova sdk https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-installation.html

**Comment by bhahirathan-mb-11956** [comment]
Hi @alaaahmedmu ,

We apologize for the inconvenience caused. The API mentioned is currently not supported in Cordova. However, we are working to include it in the next immediate update.

Regards,
Bhahirathan M,
Zoho SalesIQ.

**Comment by alaaahmedmu** [comment]
Thank you @bhahirathan-mb-11956 for your response. So when is it expected to be added in the next release?

Another questions, is there any available API that would expose if the user can start new chart based on the business hours or not?

**Comment by bhahirathan-mb-11956** [comment]
Hi @alaaahmedmu,
 
We have supported the API you have mentioned above. Kindly go through the code snippet below.
 
```
ZohoSalesIQ.Chat.isChatEnabled((success) => {
    if (success) {
    
    } else {
    
    }
});
```
 
To initiate the chat based on business hours, we suggest the ["Launcher.setVisibilityModeToCustomLauncher"](https://www.zoho.com/salesiq/help/developer-guides/cordova-ionic-sdk-launcher-set-visibility-custom-launcher.html) API and the ["EVENT.HANDLE_CUSTOM_LAUNCHER_VISIBILITY"](https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-sdk-add-event-listener.html#handle-custom-launcher-event:~:text=EVENT.HANDLE_CUSTOM_LAUNCHER_VISIBILITY) event. This will trigger a boolean value according to the business hours/offline/IP block, etc., based on your SalesIQ Brand's configuration.
 
 
I hope this helps. Please feel free to write back to us at (support@zohosalesiq.com) in case of any queries.
 
Regards,
Bhahirathan M,
Zoho SalesIQ.
