### ISSUE TITLE
plugin crashes on iOS 15 devices

### ISSUE THREAD

**Issue by Burnie777** [zoho/SalesIQ-Mobilisten-Cordova#12]
Good day, I am calling this plugin in our app, it works fine on Android (to what I can see - we do not have very old android devices) and on the latest version iOS. We are having a crash on the older version(iOS 15)

The issue is that it crashes on launch, which breaks the app... (we will be ignoring Zoho for the time-being on older devices, but we would like to fix this or find a fix for this...)

The crash happens on this call in the Zoho cordova plugin on iOS side:
```
    [ZohoSalesIQ initWithAppKey:appKey accessKey:accessKey completion:^(BOOL success) {
        CDVPluginResult* pluginResult = nil;
        if(success == true){
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsBool:YES];
            [[self commandDelegate] sendPluginResult:pluginResult callbackId:command.callbackId];
        }else{
            pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_ERROR messageAsBool:NO];
            [[self commandDelegate] sendPluginResult:pluginResult callbackId:command.callbackId];
        }
    }];
```

and the error output is as follows:
```
Dispatch queue: com.apple.main-thread (0)#0	(null) in __pthread_kill ()
#1	(null) in pthread_kill ()
#2	(null) in abort ()
#3	0x104dafcd4 in specialized LiveChatDatabaseHandler.getSortDescriptors(_:) ()
#4	0x104dade1c in LiveChatDatabaseHandler.mainThreadManagedObjectContext.getter ()
#5	0x104ad4920 in LCSharedHandler.init() ()
#6	(null) in @objc LCSharedHandler.init() ()
#7	0x104addce4 in one-time initialization function for instance ()
#8	(null) in _dispatch_client_callout ()
#9	(null) in _dispatch_once_callout ()
#10	0x104dd51b8 in specialized static ZohoSalesIQ.initWithKeysPrivate(appKey:accessKey:completionHandler:) ()
#11	(null) in @objc static ZohoSalesIQ.initWithAppKey(_:accessKey:completion:) ()
#12	(null) in -[ZohoSalesIQPlugin init:] ()
#13	(null) in -[CDVCommandQueue execute:] ()
#14	(null) in -[CDVWKWebViewEngine handleCordovaMessage:] ()
#15	(null) in -[CDVWKWebViewEngine userContentController:didReceiveScriptMessage:] ()
#16	(null) in -[CDVWKWeakScriptMessageHandler userContentController:didReceiveScriptMessage:] ()
#17	(null) in ScriptMessageHandlerDelegate::didPostMessage(WebKit::WebPageProxy&, WebKit::FrameInfoData&&, API::ContentWorld&, WebCore::SerializedScriptValue&) ()
#18	(null) in WebKit::WebUserContentControllerProxy::didPostMessage(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&) ()
#19	(null) in void IPC::handleMessageAsync<Messages::WebUserContentControllerProxy::DidPostMessage, WebKit::WebUserContentControllerProxy, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&)>(IPC::Connection&, IPC::Decoder&, WebKit::WebUserContentControllerProxy*, void (WebKit::WebUserContentControllerProxy::*)(WTF::ObjectIdentifier<WebKit::WebPageProxyIdentifierType>, WebKit::FrameInfoData&&, unsigned long long, WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::CompletionHandler<void (WTF::Span<unsigned char const, 18446744073709551615ul> const&, WTF::String const&)>&&)) ()
#20	(null) in WebKit::WebUserContentControllerProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
#21	(null) in IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) ()
#22	(null) in WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) ()
#23	(null) in IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder>>) ()
#24	(null) in IPC::Connection::dispatchIncomingMessages() ()
#25	(null) in WTF::RunLoop::performWork() ()
#26	(null) in WTF::RunLoop::performWork(void*) ()
#27	(null) in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#28	(null) in __CFRunLoopDoSource0 ()
#29	(null) in __CFRunLoopDoSources0 ()
#30	(null) in __CFRunLoopRun ()
#31	(null) in CFRunLoopRunSpecific ()
#32	(null) in GSEventRunModal ()
#33	(null) in -[UIApplication _run] ()
#34	(null) in UIApplicationMain ()
#35	(null) in main ()
#36	(null) in start ()

```

My `ionic info` output is as follow:

```
Ionic:

   Ionic CLI                     : 7.2.0 
   Ionic Framework               : @ionic/angular 7.8.4
   @angular-devkit/build-angular : 16.1.2
   @angular-devkit/schematics    : 16.1.3
   @angular/cli                  : 16.1.3
   @ionic/angular-toolkit        : 10.0.0

Cordova:

   Cordova CLI       : 12.0.0 (cordova-lib@12.0.1)
   Cordova Platforms : android 12.0.1, ios 6.3.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 12 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.12.2
   ios-sim           : 8.0.2
   NodeJS            : v18.19.0 
   npm               : 10.2.3
   OS                : macOS Unknown
   Xcode             : Xcode 15.0 Build version 15A240d
```
Any Advice or guidance on this will be much appreciated...

**Comment by venkatesh-ramesh-12517** [comment]
Hello @Burnie777 

We apologize for the inconvenience. We are currently investigating this issue and will keep you posted on the same regarding the updates.

If you have any further queries, please feel free to contact us at support@zohosalesiq.com. We'll be happy to assist you.

Best regards,
Venkatesh
Zoho SalesIQ

**Comment by Burnie777** [comment]
Thank you,

I also updated the issue on github to have my “ionic info” details there as well

Regards
Bernard

From: Venkatesh R ***@***.***>
Date: Thursday, 25 April 2024 at 1:26 PM
To: zoho/SalesIQ-Mobilisten-Cordova ***@***.***>
Cc: Bernard Kruger ***@***.***>, Mention ***@***.***>
Subject: Re: [zoho/SalesIQ-Mobilisten-Cordova] plugin crashes on iOS 15 devices (Issue #12)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hello @Burnie777<https://github.com/Burnie777>

We apologize for the inconvenience. We are currently investigating this issue and will keep you posted on the same regarding the updates.

If you have any further queries, please feel free to contact us at ***@***.******@***.***>. We'll be happy to assist you.

Best regards,
Venkatesh
Zoho SalesIQ

**Comment by venkatesh-ramesh-12517** [comment]
Hello @Burnie777 

Thank you for your patience. We've addressed the crash in our latest release, version [7.0.1](https://github.com/zoho/SalesIQ-Mobilisten-Cordova/releases/tag/v7.0.1). Please update to this version to resolve the issue. 
If you encounter any further difficulties, please don't hesitate to reach out to our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) for assistance

Best regards,
Venkatesh
Zoho SalesIQ

**Comment by Burnie777** [comment]
Good day,

Thank you very much… I appreciate… I will check today and let you know if anything else comes up…

Regards
Bernard

From: Venkatesh R ***@***.***>
Date: Tuesday, 07 May 2024 at 11:27 AM
To: zoho/SalesIQ-Mobilisten-Cordova ***@***.***>
Cc: Bernard Kruger ***@***.***>, Mention ***@***.***>
Subject: Re: [zoho/SalesIQ-Mobilisten-Cordova] plugin crashes on iOS 15 devices (Issue #12)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hello @Burnie777<https://github.com/Burnie777>

Thank you for your patience. We've addressed the crash in our latest release, version 7.0.1<https://github.com/zoho/SalesIQ-Mobilisten-Cordova/releases/tag/v7.0.1>. Please update to this version to resolve the issue.
If you encounter any further difficulties, please don't hesitate to reach out to our support team at ***@***.******@***.***> for assistance

Best regards,
Venkatesh
Zoho SalesIQ

**Comment by Burnie777** [comment]
Thank you v7.0.1 fixes the issue we had on the crashes
