### ISSUE TITLE
Failed to fetch the cordova plugin with specific version

### ISSUE THREAD

**Issue by alaaahmedmu** [zoho/SalesIQ-Mobilisten-Cordova#13]
I can not install the cordova plugin with specific version.

`cordova plugin add https://github.com/zoho/SalesIQ-Mobilisten-Cordova.git@7.0.0` 

<img width="707" alt="Screenshot 2024-05-12 at 5 42 01 PM" src="https://github.com/zoho/SalesIQ-Mobilisten-Cordova/assets/132823444/1020323f-5e45-4d3f-a806-b938ba47d1ac">

**Comment by bhahirathan-mb-11956** [comment]
Hi @alaaahmedmu ,

Thanks for writing to us. It appears that the command you're using is not working for fetching a specific version of the plugin. Please try the command below and let us know if it doesn't work. 

```cordova plugin add cordova-zohosalesiq-mobilisten@7.0.0```

Regards,
Bhahirathan M
Zoho SalesIQ.
