### ISSUE TITLE
Remove usage descriptions

### ISSUE THREAD

**Issue by jpike88** [zoho/SalesIQ-Mobilisten-Cordova#2]
https://github.com/zoho/SalesIQ-Mobilisten-Cordova/blob/8f288ce9c0a558231d46121cf533cebacd7f9762/plugin.xml#L29

These override my apps' ones and invalidate the App Store submission, as they aren't acceptable for any app to have.

**Comment by Rishabh-Raghunath** [comment]
Hi @jpike88, could you help us with the complete reason for the rejection so we can understand the issue better? 
[`NSMicrophoneUsageDescription`](https://developer.apple.com/documentation/bundleresources/information_property_list/nsmicrophoneusagedescription) is required by Mobilisten to support recording voice messages.

**Comment by jpike88** [comment]
```

We noticed that your app requests the user’s consent to access the camera, but doesn’t sufficiently explain the use of the camera in the purpose string.

To help users make informed decisions about how their data is used, all permission request alerts need to specify how your app will use the requested information.
```

https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml

Even the official Cordova camera plugin doesn't explicitly have permissions, again those description messages override the ones set by the app developer, they will differ from app to app.

**Comment by Rishabh-Raghunath** [comment]
Understood. We shall have this addressed with a quick update. Thank you for the report.

**Comment by Rishabh-Raghunath** [comment]
@jpike88 We have incorporated this change with [Release 2.0.1](https://github.com/zoho/SalesIQ-Mobilisten-Cordova/releases/tag/v2.0.1) and the [Installation guide](https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-installation.html) has now been updated.

Please do make sure that all permissions required by Mobilisten have been added to the app. We have listed the permissions that are required within our installation guide.

**Comment by Rishabh-Raghunath** [comment]
We are closing this issue now. Please feel free to reach us or leave a comment if you have any further queries.
Thank you for your contribution.
