### ISSUE TITLE
iOS building sucessful, but payloads Fail

### ISSUE THREAD

**Issue by ebofi** [zoho/SalesIQ-Mobilisten-Cordova#4]
Hi.

We aee using Monaca for our Cordova app compile and android just went good and when uploading the iOS .ipa file via Transporter in apple . We are getting a error like invalid build , the asset catelog at Payload. ...../framework/mobilesten.framework/Assets.car can't be processed.
![IMG_20210627_233320](https://user-images.githubusercontent.com/25876216/123554915-18751e80-d7a0-11eb-9970-cfdfe4be39b5.jpg)

Please update

**Comment by Rishabh-Raghunath** [comment]
Hi @ebofi, could you share the version of Xcode that is installed or selected for Command-line tools in your machine?
You can find the selected version by navigating to `Xcode` → `Preferences` → `Locations` → `Command Line Tools`.

Attaching an image of the setting for your reference.

<img width="844" alt="Screenshot 2021-06-27 at 11 51 33 PM" src="https://user-images.githubusercontent.com/55278408/123555489-971f8b00-d7a3-11eb-8af5-09e6e6072c69.png">

**Comment by ebofi** [comment]
Hi 

We are using Latest xcode which is available on Monaca Cloud 
[](url)

**Comment by ebofi** [comment]
![Uploading IMG_20210628_010642.jpg…]()

**Comment by ebofi** [comment]
![IMG_20210628_010642](https://user-images.githubusercontent.com/25876216/123557216-4745c180-d7ad-11eb-876b-a0f24b0be111.jpg)

**Comment by Rishabh-Raghunath** [comment]
Would it be possible for you to try archiving the app using Xcode 12.x and then proceed for deployment to TestFlight locally?
The minimum version of iOS required to run Mobilisten needs to be set to iOS 10.0 as well.

**Comment by ebofi** [comment]
> Would it be possible for you to try archiving the app using Xcode 12.x and then proceed for deployment to TestFlight locally?
> The minimum version of iOS required to run Mobilisten needs to be set to iOS 10.0 as well.

AS you can see on the above screenshot, I'm already compiling it on Xcode 12.2 Version

**Comment by Rishabh-Raghunath** [comment]
Hi @ebofi, 
As discussed over support chat, the minimum iOS deployment version for the application is currently set to iOS 8.0.
Mobilisten requires the minimum iOS deployment version to be set as iOS 10.0 or above.

Once the above change is made, we expect this issue to be resolved. We request you to make the above changes and let us know.

**Comment by Rishabh-Raghunath** [comment]
Hi @ebofi, we are closing this issue now since it has had no recent updates. 
As mentioned earlier, we expect the issue to be resolved once the minimum iOS deployment version of the project is updated to iOS 10.0. The build logs obtained from Monaca may be used to verify if the deployment target version has been set correctly. 
Please feel free to reach us in case you have further queries.
Thanks.

**Comment by ebofi** [comment]
Hi,..
We tried all things possible to make this work. But on Monaca the deployment version is sticking on 8. Not changing
