### ISSUE TITLE
"No network connection" on init with EUDC salesiq instance

### ISSUE THREAD

**Issue by felicienfrancois** [zoho/SalesIQ-Mobilisten-Cordova#9]
We migrated our salesiq instance from USDC to EUDC.
I updated android and ios keys with new ones (they have been regenerated during migration)

When initializing SalesIQ, It fail with the "No network connection" error (I have wifi connection).
Tested with both 4.1.0 and 5.1.0 on Android and IOS.
Checked the key values several times
```javascript
ZohoSalesIQ.init("myappkey_eu", "xxxxxxxxxxxxxxx", success, (error) => console.log("SalesIQ failed to init:", error));
// SalesIQ failed to init: No network connection
```

May the endpoint url be hardcoded to USDC and it fail with EU keys ?

The only adb logs I get when initializing is 
```
08-29 15:54:22.663   588  1087 W DynamiteModule: Local module descriptor class for com.google.android.gms.providerinstaller.dynamite not found.
08-29 15:54:22.675   588  1087 I DynamiteModule: Considering local module com.google.android.gms.providerinstaller.dynamite:0 and remote module com.google.android.gms.providerinstaller.dynamite:0
08-29 15:54:22.675   588  1087 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module com.google.android.gms.providerinstaller.dynamite found. Local version is 0 and remote version is 0.
```
Not sure if its useful or related

**Comment by bhahirathan-mb-11956** [comment]
Hi @felicienfrancois,

Thanks for contacting us. We show "No network connection" toast only when there is no internet, so we recommend you to check whether the device/emulator has working internet connection (Check the proxy/DNS). If the issue persists, please write us at (support@zohosalesiq.com). We will be happy to help you. 

Thanks,
Bhahirathan M
Zoho SalesIQ.

**Comment by felicienfrancois** [comment]
As stated in my report, the device have an internet connection for sure. The app is accessing internet without any issue and I have other plugin which access internet without any issue.

Also, all users of my app have the same issue.

I don't have any popup nor visible error message. I only see the reported error "No internet connection" in error logs, from the error callback of ZohoSalesIQ.init.

Additionally, it was perfectly working till July 2023, before our datacenter migration from USDC to EUDC which happened start of august. We had plenty of similar errors with other zoho products where endpoint urls changed and it broke every integration, so I suspect this is the root cause.

I will contact support@zohosalesiq.com to share my details.
